# we can lint, test and build at the same time.

steps:
    # install packages
    - name: 'aredwood/env'
      id: "packages"
    
    # unit test
    - name: 'aredwood/env'
      args: ['yarn','run','test']
      waitFor: ["packages"]
    # lint
    - name: 'aredwood/env'
      args: ['yarn','run','lint']
      waitFor: ['packages']
    # compile
    - name: 'aredwood/env'
      args: ['yarn','run','build']
      waitFor: ['packages']
    
    # send it 
    - name: "google/cloud-sdk"
      args: ["bash", "./deploy.sh", "$BRANCH_NAME"]
      